export const largeInvestorData = [
  {
    name: "4Di Capital",
    location: "Africa",
    description: "South African-based early-stage VC focusing on tech startups",
    website: "https://4dicapital.com",
    stage: "Seed, Early",
    thesis: "Invest in scalable African innovation and technology",
    focus: ["Technology", "SaaS"],
    active_status: "Active",
    hq_country: "South Africa",
    investmentRange: "$100K–$1M",
    notes: "One of leading African seed-stage VCs",
    linkedin: "https://linkedin.com/company/4di-capital",
    email: "info@4dicapital.com",
    type: "VC"
  },
  {
    name: "4DX Ventures",
    location: "Africa",
    description: "Africa-focused early-stage venture capital",
    website: "https://www.4dxventures.com",
    stage: "Seed, Early",
    thesis: "Funding technology-driven African startups",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "Nigeria",
    investmentRange: "$100K–$1M",
    notes: "Focus on Nigerian tech ecosystem",
    linkedin: "https://linkedin.com/company/4dx-ventures",
    email: "info@4dxventures.com",
    type: "VC"
  },
  {
    name: "500 Startups",
    location: "Global, including Africa",
    description: "Global early-stage VC and accelerator",
    website: "https://500.co",
    stage: "Seed, Pre-Seed",
    thesis: "Early-stage tech startups with global potential",
    focus: ["Technology", "SaaS", "Fintech"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "$50K–$1.5M",
    notes: "One of the world's largest seed-stage funds",
    linkedin: "https://linkedin.com/company/500startups",
    email: "contact@500.co",
    type: "Accelerator"
  },
  {
    name: "Acasia Ventures",
    location: "East Africa",
    description: "Nairobi-based VC investing in early to growth-stage companies",
    website: "https://acasiaventures.com",
    stage: "Seed, Growth",
    thesis: "Supporting innovation and growth in East Africa",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "Kenya",
    investmentRange: "$250K–$5M",
    notes: "Strong focus on African tech ecosystem",
    linkedin: "https://linkedin.com/company/acasiaventures",
    email: "info@acasiaventures.com",
    type: "VC"
  },
  {
    name: "Accion Labs",
    location: "Global, focus Africa",
    description: "Fintech innovation venture arm of global nonprofit Accion",
    website: "https://www.accion.org",
    stage: "Seed, Growth",
    thesis: "Financial inclusion through tech innovation",
    focus: ["Fintech"],
    active_status: "Active",
    hq_country: "USA/Global",
    investmentRange: "$100K–$10M",
    notes: "Connects startups with global financial inclusion",
    linkedin: "https://linkedin.com/company/accion",
    email: "info@accion.org",
    type: "VC"
  },
  {
    name: "Act Venture Capital",
    location: "Africa",
    description: "African early-stage venture capital fund",
    website: "https://act.capital",
    stage: "Seed, Early",
    thesis: "Invest in scalable African innovation and technology",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "South Africa",
    investmentRange: "$100K–$1M",
    notes: "Invests in scalable technology solutions",
    linkedin: "https://linkedin.com/company/act-venture-capital",
    email: "info@act.capital",
    type: "VC"
  },
  {
    name: "Action Hero Ventures",
    location: "Africa",
    description: "African-focused VC funding early-stage, impact-driven startups",
    website: "http://actionheroventures.com",
    stage: "Seed, Early",
    thesis: "Empower African founders focusing on social impact",
    focus: ["Technology", "Impact"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$50K–$500K",
    notes: "Founder-first investment approach",
    linkedin: "https://linkedin.com/company/actionheroventures",
    email: "info@actionheroventures.com",
    type: "VC"
  },
  {
    name: "Acuity",
    location: "Africa",
    description: "African tech venture capital with data-driven approach",
    website: "https://acuityvc.com/",
    stage: "Seed, Early",
    thesis: "Data science focusing on African tech innovation",
    focus: ["Technology", "AI"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$250K–$7M",
    notes: "Specializes in AI-driven startups",
    linkedin: "https://linkedin.com/company/acuityvc",
    email: "info@acuityvc.com",
    type: "VC"
  },
  {
    name: "Acumen",
    location: "Global, focus Africa",
    description: "Global impact investing fund focused on social enterprises",
    website: "https://acumen.org",
    stage: "Seed, Growth",
    thesis: "Investments addressing poverty with high social impact",
    focus: ["Impact Investing"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "$100K–$5M",
    notes: "Pioneer in impact investing",
    linkedin: "https://linkedin.com/company/acumen",
    email: "contact@acumen.org",
    type: "VC"
  },
  {
    name: "AfricInvest",
    location: "Africa",
    description: "Pan-African private equity and VC focused on mid-market and growth companies",
    website: "https://africinvest.com/",
    stage: "Growth, Expansion",
    thesis: "Supporting SMEs and growth companies across Africa",
    focus: ["Various"],
    active_status: "Active",
    hq_country: "Tunisia",
    investmentRange: "$5M–$100M",
    notes: "One of the largest African PE firms",
    linkedin: "https://linkedin.com/company/africinvest",
    email: "info@africinvest.com",
    type: "PE"
  },
  {
    name: "African Coinvestment Syndicate",
    location: "Africa",
    description: "Fund for co-investment in African growth companies",
    website: "https://acsinvestments.com/",
    stage: "Growth",
    thesis: "Partnership syndicate supporting mid-sized African businesses",
    focus: ["Various"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "Varies",
    notes: "Non-traditional VC syndicate",
    linkedin: "https://linkedin.com/company/acs",
    email: "info@acsinvestments.com",
    type: "Other"
  },
  {
    name: "Aganza Capital",
    location: "Africa",
    description: "African VC fund investing in innovative startups",
    website: "https://aganza.com/",
    stage: "Seed, Early",
    thesis: "Data-centric African tech investments",
    focus: ["Technology", "SaaS"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$100K–$3M",
    notes: "Focus on scalable African tech",
    linkedin: "https://linkedin.com/company/aganza-capital",
    email: "contact@aganza.com",
    type: "VC"
  },
  {
    name: "Algebra Ventures",
    location: "MENA, Africa",
    description: "Leading MENA VC specializing in tech innovations",
    website: "https://algebraventures.com/",
    stage: "Seed, Growth",
    thesis: "Technology companies at seed and growth stages",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "Egypt",
    investmentRange: "$500K–$5M",
    notes: "MENA and African tech ecosystems",
    linkedin: "https://linkedin.com/company/algebra-ventures",
    email: "contact@algebraventures.com",
    type: "VC"
  },
  {
    name: "Alitheia IDF",
    location: "Africa",
    description: "Africa gender lens and impact investment fund",
    website: "https://alitheia.com/",
    stage: "Growth",
    thesis: "Empowering women-led businesses",
    focus: ["Impact", "Finance"],
    active_status: "Active",
    hq_country: "Nigeria",
    investmentRange: "$250K–$10M",
    notes: "Gender lens investing",
    linkedin: "https://linkedin.com/company/alitheia-capital",
    email: "info@alitheia.com",
    type: "VC"
  },
  {
    name: "Alpha Mundi",
    location: "Africa, Latin America",
    description: "Impact investor focusing on emerging markets",
    website: "https://alphamundigroup.com/",
    stage: "Growth",
    thesis: "Sustainable investments in developing economies",
    focus: ["Impact Investing"],
    active_status: "Active",
    hq_country: "Switzerland",
    investmentRange: "$1M–$20M",
    notes: "Multi-sector impact fund",
    linkedin: "https://linkedin.com/company/alpha-mundi",
    email: "info@alphamundi.com",
    type: "VC"
  },
  {
    name: "Antler",
    location: "Global, Africa",
    description: "Global early-stage VC and startup generator",
    website: "https://www.antler.co/",
    stage: "Pre-seed, Seed",
    thesis: "Global talent-driven startup funding",
    focus: ["Technology", "Various"],
    active_status: "Active",
    hq_country: "Global",
    investmentRange: "$100K–$1M",
    notes: "Global presence with African focus",
    linkedin: "https://linkedin.com/company/antler",
    email: "africa@antler.co",
    type: "VC"
  },
  {
    name: "ARM Techstars Accelerator",
    location: "Africa",
    description: "Accelerator supporting technology startups in Africa and globally",
    website: "https://armtechstars.com/",
    stage: "Accelerator",
    thesis: "Supporting African tech entrepreneurs",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "Nigeria",
    investmentRange: "Program-based",
    notes: "Joint venture accelerator",
    linkedin: "https://linkedin.com/company/armtechstars",
    email: "info@armtechstars.com",
    type: "Accelerator"
  },
  {
    name: "Bamboo Capital Partners",
    location: "Africa, Asia",
    description: "Impact-focused VC investing in Africa and Asia",
    website: "https://bamboocp.com/",
    stage: "Seed, Growth",
    thesis: "Inclusive finance and sustainable investments",
    focus: ["Impact", "Finance"],
    active_status: "Active",
    hq_country: "Luxembourg",
    investmentRange: "$100K–$10M",
    notes: "Hybrid impact and financial fund",
    linkedin: "https://linkedin.com/company/bamboo-capital-partners",
    email: "info@bamboocp.com",
    type: "VC"
  },
  {
    name: "BECO Capital",
    location: "MENA, Africa",
    description: "Early-stage VC focused on MENA and African tech startups",
    website: "https://becocapital.com/",
    stage: "Seed, Early",
    thesis: "Building tech startups with regional focus",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "UAE",
    investmentRange: "$100K–$3M",
    notes: "Regional tech fund",
    linkedin: "https://linkedin.com/company/beco-capital",
    email: "info@becocapital.com",
    type: "VC"
  },
  {
    name: "Beta Ventures",
    location: "Africa",
    description: "Early-stage VC investing in African startups",
    website: "https://betaventures.com/",
    stage: "Seed",
    thesis: "Supporting African technology startups",
    focus: ["Technology"],
    active_status: "Active",
    hq_country: "Kenya",
    investmentRange: "$50K–$500K",
    notes: "Focused on East Africa",
    linkedin: "https://linkedin.com/company/beta-ventures",
    email: "info@betaventures.com",
    type: "VC"
  },
  {
    name: "Better VC",
    location: "Africa",
    description: "African early-stage deep tech VC",
    website: "https://better.vc/",
    stage: "Seed, Early",
    thesis: "Investing in African tech startups addressing major problems",
    focus: ["Deep Tech"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$100K–$500K",
    notes: "Focus on AI, deep tech",
    linkedin: "https://linkedin.com/company/better-vc",
    email: "info@better.vc",
    type: "VC"
  },
  {
    name: "Beyond Capital",
    location: "Africa",
    description: "Impact investing firm focused on sustainable growth",
    website: "https://beyondcapital.com/",
    stage: "Growth",
    thesis: "Inclusive and sustainable investments",
    focus: ["Impact Investing"],
    active_status: "Active",
    hq_country: "USA/Africa",
    investmentRange: "$1M-$10M",
    notes: "Impact focused VC",
    linkedin: "https://linkedin.com/company/beyond-capital",
    email: "info@beyondcapital.com",
    type: "VC"
  },
  {
    name: "Black Coffee",
    location: "Africa",
    description: "Pan-African early-stage venture capital fund",
    website: "https://blackcoffee.co.za/",
    stage: "Seed, Early",
    thesis: "Consumer tech and digital services",
    focus: ["Consumer Tech"],
    active_status: "Active",
    hq_country: "South Africa",
    investmentRange: "$100K-$1M",
    notes: "One of largest African early-stage VC",
    linkedin: "https://linkedin.com/company/black-coffee",
    email: "info@blackcoffee.co.za",
    type: "VC"
  },
  {
    name: "Blue Haven Initiative",
    location: "Africa",
    description: "Impact investing fund driving inclusive growth",
    website: "https://bluehaveninitiative.com/",
    stage: "Seed, Growth",
    thesis: "Impact investing with emphasis on sustainable solutions",
    focus: ["Impact Investing"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "$500K-$15M",
    notes: "Focus on social and environmental impact",
    linkedin: "https://linkedin.com/company/blue-haven-initiative",
    email: "info@bluehaveninitiative.com",
    type: "VC"
  },
  {
    name: "Bold Angel Fund",
    location: "Africa",
    description: "Angel funding for African tech entrepreneurs",
    website: "http://boldangelfund.com/",
    stage: "Seed, Angel",
    thesis: "Early-stage investments in African founders",
    focus: ["Tech"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$10K-$200K",
    notes: "Angel network model",
    linkedin: "https://linkedin.com/company/bold-angel-fund",
    email: "info@boldangelfund.com",
    type: "Angel"
  },
  {
    name: "Camel Ventures",
    location: "East Africa",
    description: "Kenya-based early-stage tech VC",
    website: "http://camelventures.co.ke/",
    stage: "Seed",
    thesis: "Technology startups in East Africa",
    focus: ["Tech"],
    active_status: "Active",
    hq_country: "Kenya",
    investmentRange: "$50K-$500K",
    notes: "Offers hands-on support",
    linkedin: "https://linkedin.com/company/camelventures",
    email: "info@camelventures.co.ke",
    type: "VC"
  },
  {
    name: "Capria Ventures",
    location: "Africa, Asia",
    description: "Global venture capital focusing on emerging markets",
    website: "https://capria.vc/",
    stage: "Seed, Growth",
    thesis: "Supporting impact and tech startups in emerging markets",
    focus: ["Impact", "Fintech"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "$1M-$3M",
    notes: "Specialized in emerging markets",
    linkedin: "https://linkedin.com/company/capria-ventures",
    email: "info@capria.vc",
    type: "VC"
  },
  {
    name: "Catalyst Fund",
    location: "Global",
    description: "Fintech accelerator and investor focusing on emerging markets",
    website: "https://catalyst-fund.com/",
    stage: "Seed, Early",
    thesis: "Enabling innovative fintech solutions",
    focus: ["Fintech"],
    active_status: "Active",
    hq_country: "UK",
    investmentRange: "Program-based",
    notes: "Accelerator and seed funding",
    linkedin: "https://linkedin.com/company/catalyst-fund",
    email: "info@catalyst-fund.com",
    type: "Accelerator"
  },
  {
    name: "CDC Group",
    location: "Africa",
    description: "UK’s development finance institution focused on Africa",
    website: "https://britishinternationalinvestment.co.uk/",
    stage: "Growth",
    thesis: "Supporting private sector growth and development",
    focus: ["Multi-sector"],
    active_status: "Active",
    hq_country: "UK",
    investmentRange: "$1M-$150M",
    notes: "Now British International Investment",
    linkedin: "https://linkedin.com/company/british-international-investment",
    email: "info@bii.co.uk",
    type: "PE"
  },
  {
    name: "Chan Zuckerberg Initiative",
    location: "Global",
    description: "Philanthropic organization funding impact-driven initiatives",
    website: "https://chanzuckerberg.com/",
    stage: "Grant, Equity",
    thesis: "Supporting tech innovation and education",
    focus: ["Health", "Education", "Tech"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "Grant, Equity",
    notes: "Philanthropy focused",
    linkedin: "https://linkedin.com/company/chan-zuckerberg-initiative",
    email: "contact@chanzuckerberg.com",
    type: "VC"
  },
  {
    name: "Chinook Capital",
    location: "Africa",
    description: "African growth capital firm",
    website: "https://chinook-capital.com/",
    stage: "Growth",
    thesis: "Supporting medium to large African companies",
    focus: ["Multi-sector"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$5M-$25M",
    notes: "Focus on growth market",
    linkedin: "https://linkedin.com/company/chinookcapital",
    email: "info@chinook-capital.com",
    type: "VC"
  },
  {
    name: "Choose Africa",
    location: "Africa",
    description: "Investment platform supporting African startups",
    website: "https://chooseafrica.com/",
    stage: "Early, Growth",
    thesis: "Connecting startups to funding, advisors, and networks",
    focus: ["Multi-sector"],
    active_status: "Active",
    hq_country: "Africa",
    investmentRange: "$100K-$2M",
    notes: "Growing network support",
    linkedin: "https://linkedin.com/company/chooseafrica",
    email: "info@chooseafrica.com",
    type: "VC"
  },
  {
    name: "Commerce Ventures",
    location: "Global, Africa",
    description: "Early-stage VC focusing on fintech and commerce",
    website: "https://commerceventures.com/",
    stage: "Seed, Early",
    thesis: "Empowering commerce and financial service innovators",
    focus: ["Fintech"],
    active_status: "Active",
    hq_country: "USA",
    investmentRange: "$500K-$10M",
    notes: "Investor in leading fintech startups",
    linkedin: "https://linkedin.com/company/commerceventures",
    email: "info@commerceventures.com",
    type: "VC"
  },
  {
    name: "Consonance Investment Managers",
    location: "Africa",
    description: "Pan-African multi-stage VC",
    website: "https://consonanceinv.com/",
    stage: "Seed, Growth",
    thesis: "Supporting innovative African tech entrepreneurs",
    focus: ["Tech"],
    active_status: "Active",
    hq_country: "Nigeria",
    investmentRange: "$100K-$3M",
    notes: "Strong local presence",
    linkedin: "https://linkedin.com/company/consonanceinvestmentmanagers",
    email: "info@consonanceinv.com",
    type: "VC"
  },
  {
    name: "Convergence Partners",
    location: "Africa",
    description: "Growth capital fund investing in Africa",
    website: "https://convergencepartners.com/",
    stage: "Growth",
    thesis: "Supporting growing private sector firms",
    focus: ["Consumer", "Finance"],
    active_status: "Active",
    hq_country: "South Africa",
    investmentRange: "$10M-$50M",
    notes: "Diversified portfolio",
    linkedin: "https://linkedin.com/company/convergence-partners",
    email: "info@convergencepartners.com",
    type: "PE"
  }
];
